queue_rules:
  - name: default
    conditions:
      - base=main
      - check-success=build-deploy-docs
      - check-success=lint
      - check-success=dev-deps (macos-14, 3.12)
      - check-success=dev-deps (ubuntu-24.04, 3.12)
      - check-success=dev-deps (windows-2022, 3.12)
      - check-success=tests (macos-14, 3.12)
      - check-success=tests (ubuntu-24.04, 3.12)
      - check-success=tests (windows-2022, 3.12)

pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
      - label=dependencies
      - check-success=build-deploy-docs
      - check-success=lint
      - check-success=dev-deps (macos-14, 3.12)
      - check-success=dev-deps (ubuntu-24.04, 3.12)
      - check-success=dev-deps (windows-2022, 3.12)
      - check-success=tests (macos-14, 3.12)
      - check-success=tests (ubuntu-24.04, 3.12)
      - check-success=tests (windows-2022, 3.12)
    actions:
      queue:
        name: default
